controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_cont:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_position_cont:
      type: position_controllers/JointGroupPositionController

diff_cont:
  ros__parameters:

    publish_rate: 30.0 # You can set this higher than the controller manager update rate, but it will be throttled
    base_frame_id: base_link

    left_wheel_names: ['left_wheel']
    right_wheel_names: ['right_wheel']
    wheel_separation: 0.2909
    wheel_radius: 0.04

    use_stamped_vel: false

    # linear.x.has_velocity_limits: true
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: 1.0
    # linear.x.min_velocity: 0.0
    # linear.x.max_acceleration: 0.0
    # linear.x.min_acceleration: 0.0
    # linear.x.max_jerk: 0.0
    # linear.x.min_jerk: 0.0

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: 0.0
    # angular.z.min_velocity: 0.0
    # angular.z.max_acceleration: 0.0
    # angular.z.min_acceleration: 0.0
    # angular.z.max_jerk: 0.0
    # angular.z.min_jerk: 0.0

# joint_trajectory_cont:
#   ros__parameters:
  
#     joints:
#       - cam_arm_pan_continuous
#       - cam_arm_tilt_continuous
#     interface_name: position
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity

forward_position_cont:
  ros__parameters:
    base_frame_id: base_link
    joints:
      - camera_pan_joint
      - camera_tilt_joint
    interface_name: position